language: node_js

node_js:
  - 6
  - 8
  - 10
  - 12

before_install:
  - phantomjs --version

before_script:
  - npm install -g grunt-cli

branches:
  only:
    - master
    - dev
    - pattern-engines
